codeready-toolchain/toolchain-cicd

toolchain-pipeline/01-toolchain-cd-tasks.yaml
use one step per task where possible to limit the usage of the resources/limits
=> chore: use one step per task where possible

toolchain-pipeline/01-toolchain-cd-tasks.yaml, toolchain-pipeline/pipeline/toolchain-cd-pipeline.yaml
When member-operator repo is being built, then push also the member-operator-webhook repo to quay
=> feat: push also member-operator-webhook image

prepare-tools-action/action.yml
need to downgrade since 1.16.x releases are broken for Ubuntu
=> fix: use opm 1.15.3

release-operator-action/action.yml
=> fix: use prod env when doing releases

scripts/cd/olm-setup.sh, scripts/ci/manage-host-operator.sh, scripts/ci/manage-member-operator.sh
make the scripts more user-friendly and add help & reading parameters
=> make the scripts more user-friendly

checkout-code/action.yml
GH action that will checkout code from PR based either on a PR event or comment in the particular PR. This will help us to trigger actions based on `/retest` comment
=> feat: add checkout code GH composite action

scripts/add-cluster.sh
Related PR: https://github.com/codeready-toolchain/api/pull/256
=> Remove hostoperatorconfig and registrationservice CRDs

scripts/add-cluster.sh
This PR adds the toolchainevents resource to the host operator
=> Added toolchainevents to add-cluster.sh

scripts/add-cluster.sh
=> feat: Space CRD

scripts/ci/manage-operator.sh, scripts/ci/wait-until-is-installed.sh
extracts the wait functionality to separate script so it can be used independently. 
related PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/422
=> feat: extract wait functionality to another script

scripts/add-cluster.sh
add SpaceBindings to ToolchainCluster role
related to https://github.com/codeready-toolchain/api/pull/287
=> chore: add SpaceBindings to ToolchainCluster role

scripts/ci/manage-host-operator.sh, scripts/ci/manage-member-operator.sh
=> fix: use  as env var

scripts/ci/manage-operator.sh
=> fix: build and push using IMAGE_BUILDER var

scripts/add-cluster.sh
add more logs to find the place where (and ideally why) it fails in CI https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/codeready-toolchain_toolchain-e2e/465/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1487098804241960960
=> add more logs to add-cluster.sh script

scripts/ci/manage-operator.sh
https://coreos.slack.com/archives/CHK0J6HT6/p1645460816213859
=> ci: after pairing print log for the last three commits

prepare-tools-action/action.yml
upgrade operator-sdk and opm binaries
=> feat: update operator-sdk to 1.16.0

scripts/ci/manage-operator.sh
otherwise, it doesn't perform the whole merge and leaves the branch uncommitted which can lead to unexpected failures in e2e tests
=> fix: use only fast-forward when merging master with paired PR

scripts/ci/manage-operator.sh
this could limit some flakiness, but won't probably solve the main problem
=> feat: wait for CatalogSource to be ready before installing operator

scripts/ci/collect-logs.sh, scripts/ci/manage-operator.sh, scripts/ci/wait-until-is-installed.sh
This should collect logs of all pods that occur in the operator namespaces +  `openshift-operator-lifecycle-manager`
=> feat: collect all logs

scripts/add-cluster.sh
Add the new UserTier CRD to the host operator role.
Related PR: https://github.com/codeready-toolchain/api/pull/302
=> Add UserTier resource

scripts/add-cluster.sh
Related Issue: https://issues.redhat.com/browse/CRT-1500
=> Remove TemplateUpdateRequest

scripts/add-cluster.sh
Related PR: https://github.com/codeready-toolchain/api/pull/312
=> Remove changetierrequests from add-cluster script

.gitignore, scripts/add-cluster.sh
Required for reg-service proxy for token verification
Another prerequisite for the proxy cache PR: https://github.com/codeready-toolchain/registration-service/pull/275
=> Add cluster role for member SA

scripts/add-cluster.sh
=> fix: don't use KUBECONFIG variable

prepare-tools-action/action.yml
=> update Operator SDK to v1.21.0

prepare-tools-action/action.yml
Update operator-sdk and opm to v1.23
=> update operator-sdk and opm to v1.23

scripts/add-cluster.sh
Adds impersonate rule to toolchaincluster's ClusterRole.
Issue: https://issues.redhat.com/browse/CRT-1461
=> Add additional permissions to member toolchainclusters

scripts/add-cluster.sh
improve token and secrets handling - don't rely on the OpenShift cluster version, it may happen that the version is not visible. it rather relies on the secret format and its availability 
related PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/664
=> improve token and secrets handling

prepare-tools-action/action.yml, scripts/add-cluster.sh
upgrade operator-registry and operator sdk
Jira story: https://issues.redhat.com/browse/CRT-1740
=> upgrade operator-registry and operator sdk

scripts/add-cluster.sh
Enable member SA to manage secrets
Jira: https://issues.redhat.com/browse/ASC-258
Related PRs:
=> feat: Implement "copy secret" functionality in SpaceRequest controller

scripts/add-cluster.sh
This PR add a new API type SpaceBindingRequest, which will allow admin users to manage permissions on their own Space, and grant access to other users.
Jira: https://issues.redhat.com/browse/ASC-394
=> feat: add spacebindingrequest type

scripts/add-cluster.sh, scripts/ci/manage-operator.sh
Fix for https://issues.redhat.com/browse/RHTAPBUGS-1112
as suggested in https://redhat-internal.slack.com/archives/C3VS0LV41/p1706002407122759 
we should probably add this to the stage and prod configs as well.
=> fix catalog source issue on hypershift 4.14

scripts/ci/manage-host-operator.sh, scripts/ci/manage-member-operator.sh, scripts/ci/manage-operator.sh
https://redhat-internal.slack.com/archives/C06MJ2DVBU4/p1713196090341829
=> add ability to define a fixed tag to be used for built images

scripts/add-cluster.sh
Reverts codeready-toolchain/toolchain-cicd#111
depends on these PRs to be merged first:
https://github.com/codeready-toolchain/host-operator/pull/1041
https://github.com/codeready-toolchain/toolchain-e2e/pull/994
https://github.com/codeready-toolchain/member-operator/pull/576
=> Revert "add caBundle to support backward compatibility"

scripts/add-cluster.sh
https://redhat-internal.slack.com/archives/C06MJ2DVBU4/p1721729885818389?thread_ts=1721651530.593729&cid=C06MJ2DVBU4
=> use correct kubeconfig when waiting for SA

scripts/add-cluster.sh
add kubeconfig to ToolchainCluster secret so we can drop the migration logic from the controllers
=> add kubeconfig to ToolchainCluster secret

scripts/add-cluster.sh
:man_facepalming: 
[KUBESAW-161](https://issues.redhat.com/browse/KUBESAW-161)
=> fix: add missing insecure field

CODEOWNERS
=> project: add Rafaela, Feny, Joel, Panos and Lukas to CODEOWNERS

CODEOWNERS
JIRA: https://issues.redhat.com/browse/SANDBOX-1043
=> chore: Remove Kanika from owners
