sync/04-toolchain-cicd-binding.yaml
sync/06-trigger-templates.yaml

don't use the `body.pull_request.head.ref` as it contains the branch name which doesn't work when PR goes from a forked repo.

fix: don't use gitref (branch name in case of PR)

---

toolchain-pipeline/01-toolchain-cd-tasks.yaml

Since we use the latest OSP we can rely on the `depth` field with the value set to `0`, thus we can drop some steps that were used as a workaround.

feat: rely on depth=0 in PipelineResource

---

toolchain-pipeline/01-toolchain-cd-tasks.yaml

the reason is that the builds were sometimes hitting the quota.

fix: increase the memory while building tools and sha images

---

common/sa.yaml
sync/06-trigger-templates.yaml

we need to use the `pipeline` SA in sync pipeline because the `image-pusher` doesn't have permissions to modify the tekton resources. Thus I had to assign the docker credentials to the `pipeline` SA as well so he is able to push the `buildah-short-sha` image to quay

fix: use pipeline SA in sync

---

Dockerfile.tools
sync/01-apply-resources-task.yaml
sync/03-sync-toolchain-cd-pipeline.yaml

Adds Dockerfile.tools that is built on top of buildah and containing opm binary - this will be used for pushing bundle and index images to quay

feat: add Dockerfile.tools based on buildah and containing opm

---

Dockerfile.tools
sync/01-apply-resources-task.yaml

opm doesn't fully support buildah for working with index images - we need to use podman instaed

fix: use podman instead of buildah that is not supported by opm index

---

toolchain-pipeline/01-toolchain-cd-tasks.yaml
toolchain-pipeline/03-toolchain-cd-pipeline-template.yaml
toolchain-pipeline/pipeline/toolchain-cd-pipeline.yaml

This PR changes the step that generates and pushes new manifests - there are two steps now:
* `generate-cd-release-manifests` 
* generates the manifests for the next release
* pushes the manifests as an application to quay
* `push-bundle-and-index-image` 
* uses the generated manifests from the previous step and builds and pushes bundle image + adds the bundle to index image

chore: push new manifests as app and as bundle image

---

toolchain-pipeline/01-toolchain-cd-tasks.yaml

* ignores any errors while pushing manifests as an app to quay
* increases the cpu limit to make the generation faster

chore: ignore app push errors & increase cpu limit

---

sync/05-eventlistener.yaml
toolchain-pipeline/04-eventlistener.yaml

The `name` in `EventListener` was deprecated some time ago and in 4.6 it was completely removed. I replaced it with `ref`

fix: replace removed name with ref

---

sync/06-trigger-templates.yaml
toolchain-pipeline/03-toolchain-cd-pipeline-template.yaml

It looks like that in the new version of pipelines, we need to reference a TriggerTemplate when using the parameters

fix: we need to newly reference the TriggerTemplate

---

prepare-tools-action/action.yml
release-operator-action/action.yml

adds two composite GH actions:
1. An action for installing necessary tools like operator-sdk, podman, and opm
2. An action that releases a new version of the Toolchain operator

feat: add composite GH actions

---

prepare-tools-action/action.yml

use latest version of opm - 1.16.1
related PR: https://github.com/codeready-toolchain/api/pull/218

chore: use opm 1.16.1

---

prepare-tools-action/action.yml
publish-operators-for-e2e-tests/action.yml

* Updates CD action to use latest operator-sdk
* Adds new GH action that builds & pushes operator bundles for e2e tests to quay

feat: migrate CICD to operator-sdk 1.8.0

---

release-operator-action/action.yml

I cannot initialize the index image manually, because I would need to reference the name of the bundle images that already exist and are in use.
Will set remove it as soon as I will make the first releases for both new index images

chore: set FIRST_RELEASE to true to initialize the index images

---

publish-operators-for-e2e-tests/action.yml

because we need to know the name of the author of a PR - right now, we use `GITHUB_ACTOR` var provided by the GH Actions env, however, that var contains a name of a persons who triggers the event (for example clicks on a button in GH Actions UI) and not the owner of the PR

fix: add author var

---

scripts/add-cluster.sh
scripts/cd/enrich-by-envs-from-yaml.sh
scripts/cd/generate-cd-release-manifests.sh
scripts/cd/olm-setup.sh
scripts/cd/push-bundle-and-index-image.sh
scripts/ci/manage-host-operator.sh
scripts/ci/manage-member-operator.sh
scripts/ci/manage-operator.sh

copies all scripts from other repositories:
* api
* toolchain-common
* toolchain-e2e
so it's all in one repo and it's easier to manage.
It also slightly changes the way it installs the operator.
In the following PRs I will:
* redirect all logic to use this new location
* remove the scripts from the other repositories

feat: add all ci/cd scripts

---

scripts/ci/manage-operator.sh

for this type of use-cases we don't need a dynamic channel name - let's just hard-code it to `alpha`

fix: use hard-coded channel name

---

scripts/ci/manage-operator.sh

if the operator is already deployed in the namespace, then before installing it it deletes all OLM related resources which will cause:
* uninstall of the operator
* deletion of the deployment
so the script can force OLM to deploy the new version of the operator by creating new resources

feat: allow redeploy - local environment

---

scripts/add-cluster.sh

I've attempted to run e2e tests on a IBM cluster and found an issue in the regexp, since the API server URL does not start with "api." in those environments.
This patch allows extracting the hostname even in the following cases:
```
"https://api.server.domain.net:6443"
"https://server.domain.net:6443"
"https://server.domain.net:6443/path"
"https://server.domain.net/path"
"https://server.domain.net"
```
In all cases it extracts "server.domain.net".

chore: fix regexp to allow working on different kinds of clusters

---

scripts/ci/manage-host-operator.sh
scripts/ci/manage-member-operator.sh
scripts/ci/manage-operator.sh

This PR:
* adds support for installing the latest version from quay - without building the images from the GH repo. The latest version is used when:
* either `--deploy-latest=true` flag is set 
* or when it runs locally (`CI` var is not set) and the path to the operator directory is not provided - this means when it is not supposed to use the local copy o the operator repository (for example when running `make test-e2e`)
* enables the verbose output of the scripts only in CI  
* when it detects an already existing installation of any of the operators, then it waits until the installation is properly removed 
related PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/443

feat: support deploying latest versions from quay

---

prepare-tools-action/action.yml
scripts/cd/push-bundle-and-index-image.sh

downgrade opm - there is some incompatibility with the version of GH Actions we run and a library opm requires
it also fixes the way we construct from image

downgrade opm - problem with GH Actions image

---

publish-operators-for-e2e-tests/action.yml

when the build is triggered from a comment, then the `GITHUB_HEAD_REF` env var is not set so we need to set it explicitly.

fix: add gh-head-ref param

---

scripts/ci/wait-until-is-installed.sh

from the logs it looks like it has problems with connecting to quay repo:
```
I0319 02:23:40.617962       1 event.go:282] Event(v1.ObjectReference{Kind:"Namespace", Namespace:"", Name:"toolchain-host-19022157", UID:"1b9b3eb7-8a86-4859-9fc1-2056e7bf0e30", APIVersion:"v1", ResourceVersion:"29772", FieldPath:""}): type: 'Warning' reason: 'ResolutionFailed' error using catalog source-toolchain-host-operator-latest (in namespace toolchain-host-19022157): failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.30.202.37:50051: connect: no route to host"
```
can be either caused on OS side or on Quay side. 
Anyway, let's try to increase the timeout as a workaround

workaround: increase wait timeout

---

scripts/ci/wait-until-is-installed.sh

This reverts commit 9ffa36afb02f45792a0de19b8dd5f9467a3cfc1a. (https://github.com/codeready-toolchain/toolchain-cicd/pull/56) in favour of a better log collection method: https://github.com/codeready-toolchain/toolchain-cicd/pull/58

Revert "Print all pod logs in olm and operator ns (#56)"

---

scripts/add-cluster.sh

this flag does not exist on macOS ¯\_(ツ)_/¯

refactor: do not use '-w' flag on 'base64

---

scripts/add-cluster.sh

if the cluster is running kube 1.24 or newer, then it creates a token via `kubectl create token` command. 
it also takes the client certificate from the kubeconfig
Please, do not merge this yet - requires additional testing and one more change in toolchain-common repo

adapt cluster script to kube 1.24

---

scripts/ci/manage-host-operator.sh
scripts/ci/manage-member-operator.sh

When the builds are running as part of the openshift/release jobs, then we should always use the latest version of the operators

fix: use latest in openshift/release jobs

---

scripts/add-cluster.sh

Add SpaceRequest resources to ClusterRole that is be used by the operators.
This enables the SpaceRequest Controller to manage CRs in all namespaces and not only in the operator namespace.
Jira: https://issues.redhat.com/browse/ASC-256
Related PRs:
- api: https://github.com/codeready-toolchain/api/pull/350
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/751

feat: create the basic SpaceRequest controller skeleton

---

scripts/add-cluster.sh

to address this issue seen during local e2e testing:
`{"level":"info","ts":"2023-03-10T15:17:21.459Z","logger":"registration-service","msg":"GGM accessForSpace error routes.route.openshift.io \"member-operator-metrics-service\" is forbidden: User \"system:serviceaccount:toolchain-member-10100902:toolchaincluster-member\" cannot get resource \"routes\" in API group \"route.openshift.io\" in the namespace \"toolchain-member-10100902\"","timestamp":"Fri, 10 Mar 2023 15:17:21 +0000","commit":"32ff890"}`
upon revisiting https://github.com/codeready-toolchain/toolchain-common/pull/303 and seeing the existing presence of authenticationv1 there and the comment around verifying cached tokens, adding permissions here seems to line up with the existing permissions for creating tokenreviews in this …

PLNSRVCE-1166: add get route perms for toolchaincluster-member

---

scripts/add-cluster.sh

Grant required permissions to member operator SA so that space request controller can get/list namespace and update status and finalizer for space requests.
Jira: https://issues.redhat.com/browse/ASC-257
Related PRs:
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/770
- e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/685

Implement creation of sub-spaces in SpaceRequest controller

---

prepare-tools-action/action.yml
scripts/add-cluster.sh

After recent merge of upgrade publish operator is now failing:
https://github.com/codeready-toolchain/toolchain-e2e/actions/runs/4626650902/jobs/8183705503
seems that the version added is incorrect.
```
curl -Lo opm https://github.com/operator-framework/operator-registry/releases/download/v1.26.3-0.20220930210947-614d6a955dc0/linux-amd64-opm
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0    155      0 --:--:-- --:--:-- --:--:--   155
+ chmod +x opm
+ sudo cp opm /bin/opm
+ rm opm
+ opm version
/usr/bin/opm: line 1: Not: command not found
```

fix issue with publish operator in ci

---

scripts/add-cluster.sh

* don't rely on the namespace names that were dropped from sandbox.yaml file
* use single SA token from sandbox.yaml file
verified in e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/713

update the add-cluster.sh script to the latest changes in sandbox-sre

---

scripts/add-cluster.sh

`$TITLE`.
This is in support for https://github.com/codeready-toolchain/api/pull/397

KSPACE-28: Add spaceprovisionerconfigs to the host operator's role.

---

scripts/add-cluster.sh

This PR drop the unused parts in addcluster.sh script, and is related to https://github.com/codeready-toolchain/toolchain-e2e/pull/880

KSPACE-16: Drop the unused part in script "e2e" type SA

---

scripts/add-cluster.sh

This is Related to https://github.com/codeready-toolchain/toolchain-common/pull/359 ,
Drop the distinction between host & member ToolchainClusters

KUBESAW-45: Drop Toolchain Cluster CR type label

---

scripts/add-cluster.sh

This updates the `add-cluster.sh` to put a label on the secret linked to the ToolchainCluster that marks the secret as belonging to the ToolchainCluster.
This is currently not really used for anything but will be used in the future.
Associated PRs:
- toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/396
- api: https://github.com/codeready-toolchain/api/pull/423
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1030
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/970

KUBESAW-16: Label the secrets with the access tokens for toolchain clusters

---

scripts/add-cluster.sh

[KUBESAW-121](https://issues.redhat.com/browse/KUBESAW-121)
The logic won't get the certificates and won't set the `ToolchainCluster.spec.caBundle` anymore. In production, it's expected that this should work automatically. In dev/e2e environment we will use insecure connections only (for now until we migrate the secrets to kubeconfig format) which will be driven by 
```
ToolchainCluster.spec.disabledTLSValidations: 
- '*'
```
see https://github.com/codeready-toolchain/toolchain-common/pull/403

fix: don't set the caBundle field in ToolchainCluster.spec

---

scripts/add-cluster.sh

Just after merging the previous PR I realized that this will break e2e tests in Konflux until I merge all other PRs (in e2e, host and member)
let's add the cert for now and remove it as soon as the PRs are merged

add caBundle to support backward compatibility

---

prepare-tools-action/action.yml

Upgrades:
Tool/Library | Current Version | Updates to Version
-- | -- | --
Operator SDK | 1.25 | 1.36
Operator rehistry | 1.26.3 | 1.39.0
wrt: https://issues.redhat.com/browse/SANDBOX-686

SANDBOX-686: update operator-sdk

---

scripts/cd/olm-setup.sh

add `--replace-version` so we can explicitly define the operator version that is being replaced.
This is needed to easily fix broken releases.

add --replace-version flag

---

scripts/cd/README.adoc
scripts/cd/push-bundle-and-index-image.sh

the workaround in `handle_missing_version_in_combined_repo` doesn't work anymore - dropping it

drop broken workaround for missing operator versions

---

prepare-tools-action/action.yml

We already did the first phase of PRs to upgrade the dependencies for openshift 4.17. Now the second phase is to actually upgrade operator-sdk
Tool/Library | Current Version | Updates to Version
-- | -- | --
Operator SDK | 1.36 | 1.38
Operator registry | v1.39.0 | v1.42.0
Related PRs: 
- https://github.com/codeready-toolchain/host-operator/pull/1160
- https://github.com/codeready-toolchain/member-operator/pull/645
[SANDBOX-808](https://issues.redhat.com/browse/SANDBOX-808)

upgrade operator-sdk to 1.38

---

prepare-tools-action/action.yml

Tool/Library | Current Version | Updates to Version
-- | -- | --
Operator SDK | 1.38 | 1.39.2
Operator registry |v1.42.0 | v1.49.0
Related PRs: 
- https://github.com/codeready-toolchain/member-operator/pull/665
- https://github.com/codeready-toolchain/host-operator/pull/1170
[SANDBOX-955](https://issues.redhat.com/browse/SANDBOX-955)

SANDBOX-955: update operator-sdk
